# drivers/video/msm/mhl_v2/Makefile
#
# Copyright (c) 2012 SAMSUNG INDIA SOFTWARE OPERATIONS
# 		http://www.samsung.com/
# Manoj Prabhu B
#	prabhu.manoj@samsung.com



obj-$(CONFIG_VIDEO_MHL_TAB_V2) += sii9234.o \
