#!/sbin/sh
exec > /lk/initlog.txt 2>&1

PATH=/sbin
BAIL=0

mkdir /dev/block
mknod /dev/block/mmcblk0p15 b 179 15
echo "---"
mount -t ext4 /dev/block/mmcblk0p15 /data
echo "---"

    
if test -f /data/lk_once; then
  if test -f /data/lk_counter; then
    if [ `wc -l /data/lk_counter | awk '{ print $1 }'` -gt 3 ]; then
      BAIL=1
      rm /data/lk_counter
      echo "trip counter reached - resetting..."
    fi
    cat /data/lk_counter
  fi
  echo "tripped" >> /data/lk_counter
  if [ $BAIL -ne 1 ]; then
    /sbin/rm /data/lk_once
    /sbin/umount /data
    rm /dev/block/mmcblk0p15
    rm /charger
    rm /init
    rm /init.rc
    mv /init_samsung /init
    mv /init.rc_samsung /init.rc
    mv /etc /etc.recovery
    mv /default.prop.kernel /default.prop
    mv /sbin /sbin.recovery
    /sbin.recovery/mv /sbin.samsung /sbin
    exec /init
  fi
fi

test -f /data/lk_counter && rm /data/lk_counter
/sbin/rm /init
/sbin/mv /init_recovery /init
exec /init
