#!/system/bin/sh

# VMIN: set it to 1 to restore stock behavior of overriding voltage minimum to 1150
VMIN=0
# GPU: set it to 1 to OC 3D GPU to 480Mhz (exp only)
GPU=0

if [ $GPU -gt 0 ]; then 
  GPU=480000000
  echo $GPU > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
fi

echo $VMIN > /sys/devices/system/cpu/cpu0/cpufreq/override_vmin
