#!/system/bin/sh
mount -o rw,remount /system
cp /sbin/thermald /system/bin/thermald
mount -o ro,remount /system
echo "thermald restored to stock version. If you want leanKernel version, flash kernel again."
