#!/system/bin/sh
BB="/system/xbin/busybox"
SCRIPT="/system/etc/init.d/00leanKernel"

echo
echo "leanKernel configurator"
echo
echo "---"
echo "1) interactiveX: set screen-off max freq to 1.1Ghz."
echo "2) interactiveX: set screen-off max freq to 810Mhz (leanKernel default)."
echo "3) Overclock 3D GPU to 480Mhz (exp build only, for now)."
echo "4) Return to stock GPU max at 400Mhz (exp build only, for now)."
echo "5) Stop thermald (for running benchmarks)."
echo "6) Set display color temp to cold."
echo "7) Set display color temp to normal."
echo "8) Set display color temp to warm."
echo 
echo -n "Please enter a number between 1 and 8 (or press enter to exit): "

read option

$BB mount -o rw,remount /system /system

case $option in
  1) 
	$BB sed -i s/^SO_MAX=.*$/SO_MAX=1134000/ $SCRIPT
	$SCRIPT
	echo "interactiveX: screen off max freq set to 1134000."
	;;
  2) 
	$BB sed -i s/^SO_MAX=.*$/SO_MAX=810000/ $SCRIPT
	$SCRIPT
	echo "interactiveX: screen off max freq set to 810000 (default)."
	;;
  3) 
        $BB sed -i s/^GPU=.*$/GPU=1/ $SCRIPT
        $SCRIPT
        echo "gpu OC'ed to 480mhz."     
        ;;
  4) 
        $BB sed -i s/^GPU=.*$/GPU=0/ $SCRIPT
        $SCRIPT
        echo "gpu OC removed."  
        ;;
  5) 
	stop thermald
	echo "thermald stopped - reboot to get it back."
	;;
  6) 
	$BB sed -i s/^COLOR=.*$/COLOR=0/ $SCRIPT
	$SCRIPT
	echo "Color temp is set to Cold - turn display off/on to take effect."
	;;
  7) 
	$BB sed -i s/^COLOR=.*$/COLOR=2/ $SCRIPT
	$SCRIPT
	echo "Color temp is set to Normal - turn display off/on to take effect."
	;;
  8) 
	$BB sed -i s/^COLOR=.*$/COLOR=4/ $SCRIPT
	$SCRIPT
	echo "Color temp is set to Warm - turn display off/on to take effect."
	;;
esac
$BB mount -r /system /system
echo
