#!/system/bin/sh
BB="/system/xbin/busybox"
SCRIPT="/system/etc/init.d/00leanKernel"

echo
echo "leanKernel configurator"
echo
echo "---"
echo "1) interactiveX: set screen-off max freq to 1.1Ghz."
echo "2) interactiveX: set screen-off max freq to 810Mhz (leanKernel default)."
echo "3) Stop thermald (for running benchmarks)."
echo "4) Restart mpdecision (when cpu1 gets stuck)."
echo 
echo -n "Please enter a number between 1 and 4 (or press enter to exit): "

read option

$BB mount -o rw,remount /system /system

case $option in
  1) 
	$BB sed -i s/^SO_MAX=.*$/SO_MAX=1134000/ $SCRIPT
	$SCRIPT
	echo "interactiveX: screen off max freq set to 1134000."
	;;
  2) 
	$BB sed -i s/^SO_MAX=.*$/SO_MAX=810000/ $SCRIPT
	$SCRIPT
	echo "interactiveX: screen off max freq set to 810000 (default)."
	;;
  3) 
	stop thermald
	echo "thermald stopped - reboot to get it back."
	;;
  4) 
	$BB pkill -f mpdecision
	echo "mpdecision restarted."
	;;
esac
$BB mount -r /system /system
echo
